version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    command: ["mongod", "--bind_ip", "0.0.0.0"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - app_network

  app:
    build: .
    container_name: blog-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODBURI=${MONGODB_URI}
    volumes:
      - app_data:/app
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data:
  mongodb_config:
  app_data:
