version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - app_network

  app:
    build: docker
    container_name: blog-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODBURI=${MONGODBURI}
    volumes:
      - app_data:/app
    networks:
      - app_network

networks:
  app_network:
    driver: local

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  app_data:
    driver: local