version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/secret_mongodb_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/secret_mongodb_password
    command: [ "mongod", "--bind_ip", "0.0.0.0" ]
    ports:
      - "27017:27017"
    secrets:
      - secret_mongodb_username
      - secret_mongodb_password
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - app_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  app:
    image: teodorakovachka/kiii-blogapp:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    secrets:
      - secret_mongodb_uri
    networks:
      - app_network
    volumes:
      - app_data:/app
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  app_network:
    driver: overlay

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  app_data:
    driver: local

secrets:
  secret_mongodb_uri:
    external: true
  secret_mongodb_username:
    external: true
  secret_mongodb_password:
    external: true
