version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: [ "mongod", "--bind_ip", "0.0.0.0" ]
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - app-network

  app:
    build: .
    container_name: blog-app
    ports:
      - "3000:3000"
    environment:
      - MONGODBURI=mongodb://root:password@mongo:27017/Blogapp?authSource=admin
    depends_on:
      - mongo
    volumes:
      - app_data:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  app_data:
    driver: local
