name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master
#  workflow_run:
#    workflows: ["workflow name"]
#    types:
#      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up MongoDB container with GitHub secrets
        run: |
          docker run -d --name mongodb \
            -e MONGO_INITDB_ROOT_USERNAME=${{ secrets.SECRET_MONGODB_USERNAME }} \
            -e MONGO_INITDB_ROOT_PASSWORD=${{ secrets.SECRET_MONGODB_PASSWORD }} \
            -p 27017:27017 mongo:latest

      - name: Build Docker Image and Push to DockerHub
        run: |
          docker build --build-arg MONGODBURI=${{ secrets.SECRET_MONGODB_URI }} -t ${{ secrets.DOCKERHUB_USERNAME }}/kiii-blogapp:latest ./docker
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kiii-blogapp:latest

      - name: Deploy Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d