name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master
#  workflow_run:
#    workflows: ["workflow name"]
#    types:
#      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Swarm
        run: |
          docker swarm init

      - name: Create Docker secrets from GitHub secrets
        run: |
          echo "${{ secrets.SECRET_MONGODB_URI }}" | docker secret create secret_mongodb_uri -
          echo "${{ secrets.SECRET_MONGODB_USERNAME }}" | docker secret create secret_mongodb_username -
          echo "${{ secrets.SECRET_MONGODB_PASSWORD }}" | docker secret create secret_mongodb_password -

      - name: Build Docker Compose services
        run: |
          docker stack deploy -c docker-compose.yml mystack

      - name: Push Docker Image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kiii-blogapp:latest