name: Build and Deploy Docker Image

on:
  workflow_run:
    workflows: ["Test Docker Compose Orchestration"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGODB_USERNAME: ${{ secrets.SECRET_MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.SECRET_MONGODB_PASSWORD }}
      MONGODB_URI: ${{ secrets.SECRET_MONGODB_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image and Push to DockerHub
        run: |
          docker build --build-arg MONGODBURI=${{ secrets.SECRET_MONGODB_URI }} -t ${{ secrets.DOCKERHUB_USERNAME }}/kiii-blogapp:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kiii-blogapp:latest