name: Test Application, Build Docker Image and Push to Dockerhub

on:
  push:
    branches: [ "master" ]

jobs:
  test-node-app:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run tests
        run: npm test


  docker-compose-test:
    needs: test-node-app
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      MONGODB_USERNAME: ${{ secrets.SECRET_MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.SECRET_MONGODB_PASSWORD }}
      MONGODB_URI: ${{ secrets.SECRET_MONGODB_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Check if MONGODBURI is defined
        run: |
          if [ -z "$MONGODB_URI" ]; then
            echo "MONGODB_URI is undefined or empty"
          else
            echo "MONGODB_URI is defined"
          fi

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down

  build-and-push:
    needs: [ test-node-app,docker-compose-test ]
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image and Push to DockerHub
        run: |
          docker build --build-arg MONGODBURI=${{ secrets.SECRET_MONGODB_URI }} -t ${{ secrets.DOCKERHUB_USERNAME }}/kiii-blogapp:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kiii-blogapp:latest
